### ISSUE TITLE
Question / request for clarification

### ISSUE THREAD

**Issue by danmichaelo** [MARCspec/MARCspec#22]
Hi. Given example data

    020$cLorem$aIpsum
    020$cDolor

I expected `020$c{$a}` from example in 4.7.2 to return just `['Lorem']` (thinking 
xpath-like `020[a]/c`), but instead I got `['Lorem', 'Dolor']` (from File_MARC_Reference). Of course I'm guilty of not having read the spec thoroughly enough, but if I understand it right, this is a result of point 2 in 2.3? And that `020$c{$a}` is just a shorthand for `020$c{020$a}`?

To avoid confusion, perhaps

> Reference data content of subfield “c” of field “020”, if subfield “a” of field “020” exists.

could be clarified as

> Reference data content of subfield “c” of any field “020”, if subfield “a” of any field “020” exists (not necessarily the same field).

or something along those lines?

**Comment by cKlee** [comment]
Good question! I think the spec is not specific enough about this point. Intuitively I would expect to get only ```[Lorem]```. This would mean the reference is interpreted like:

    020[0]$c{020[0]$a} or
    020[1]$c{020[1]$a} 

Currently it is interpreted like

    020[0]$c{?020[0]$a} or
    020[0]$c{?020[1]$a} or
    020[1]$c{?020[0]$a} or
    020[1]$c{?020[1]$a} 

This looks more unexpected.

It's the same with comparison strings. I would expect the first behavior be the right one. Let's say we have a repeated subfield $c:

    020$cLorem$aIpsum$cDolor

I like to reference the subfield $c which contains the string 'rem': ```020$c{~\rem}``` This should be interpreted like:

    020$c[0]{020$c[0]~\rem} or // Lorem
    020$c[1]{020$c[1]~\rem} // null

resulting in ```[Lorem]``` and not ```[Lorem, Dolor]``` which is a result of

    020$c[0]{020$c[0]~\rem} or // Lorem
    020$c[0]{020$c[1]~\rem} or // null
    020$c[1]{020$c[0]~\rem} or // Dolor
    020$c[1]{020$c[1]~\rem}  // null

What comes out: Spec must be more specific and File_MARC_Reference must be adjusted.

**Comment by danmichaelo** [comment]
:+1: Thanks, good to hear that the result wasn't really intentional.

**Comment by horaciod** [comment]
I think that is a bug. In this example: 
020$cJohn$adirector
020$cMary
is importan only check  the presence of subfield in the first occurrence not in whole field.

**Comment by cKlee** [comment]
With 4639cee245f1ebef04107db0d71109b1efb02229 Spec is now more clear on the subject (see 2.3 MARCspec interpretation and 4.7.3 Abbreviation of fieldSpec or subfieldSpec).

**Comment by cKlee** [comment]
Solved this problem (hopefully) in https://github.com/MARCspec/File_MARC_Reference
